stages:
  - lint
  - test
  - build

.go-setup:
  before_script:
    - apk add --no-cache git make gcc musl-dev
    - go mod download
    - go mod tidy
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go/pkg/mod

lint:
  stage: lint
  extends: .go-setup
  image: golangci/golangci-lint:v2.6.1-alpine
  script:
    - golangci-lint run -v
  allow_failure: false

test:
  stage: test
  image: golang:1.24-alpine
  before_script:
    - apk add --no-cache git make gcc musl-dev
  script:
    - go mod download
    - go test -v -race ./...
  artifacts:
    expire_in: 7 days

#build:docker:
#  image:
#    name: gcr.io/kaniko-project/executor:v1.23.2-debug
#    entrypoint: [""]
#    before_script:
#      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}"
#        | base64
#        | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#    script:
#      - /kaniko/executor --context "{CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
#        --target order-manager \
#        --destination "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_SHORT_SHA}" \
#        --destination "${CI_REGISTRY_IMAGE}/app:latest"
#
#      - /kaniko/executor --context "{CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
#        --target migrator \
#        --destination "${CI_REGISTRY_IMAGE}/migrator:${CI_COMMIT_SHORT_SHA}" \
#        --destination "${CI_REGISTRY_IMAGE}/migrator:latest"
